update cloud-init

diff --git a/azure-init/scripts/cloud-init.yml b/azure-init/scripts/cloud-init.yml
--- a/azure-init/scripts/cloud-init.yml
+++ b/azure-init/scripts/cloud-init.yml
@@ -7,34 +7,43 @@ packages:
   - podman
   - python3-pip
   - git
+  - yum-utils
+  - dnf-plugins-core
+  - curl
+  - zip
+  - unzip
+  - openssl
 
 write-files:
 - path: /root/podman/podman-init.sh
 content: |
-  set -xe
-
-  [ "$(whoami)" = root ] || { sudo "$0" "$@"; exit $?; }
-
-  if [ "$(command -v pip3)" ]; then
-
-    export PATH=$PATH:${HOME}/.local/bin && \
-    source ${HOME}/.bashrc && \
-    pip3 install --user podman-compose && \
-
-    git clone https://github.com/craigthackerx/azure-challenge-solutions.git && \
-
-    cd azure-challenge-solutions/container/podman/grafana && \
-    mkdir -p grafana-data && \
-    systemctl --user enable --now dbus.socket && \
-    echo "The VM is now setup.  On your host, run vagrant ssh and then  cd azure-challenge-solutions/container/podman/ && podman-compose up -d" && \
-    cd .. && podman-compose up -d
-
-  else
-    echo "Error running user script"
-  fi
+  set -xeuo pipefail
+  
+   if [ "$(command -v pip3)" ]; then
+  
+     export PATH=$PATH:${HOME}/.local/bin && \
+  
+     git clone https://github.com/craigthackerx/azure-challenge-solutions.git && \
+  
+     pip3 install --user podman-compose && \
+  
+     cd azure-challenge-solutions/container/podman/grafana && \
+     mkdir -p grafana-data && \
+     systemctl --user enable --now dbus.socket && \
+     echo "The VM is now setup." && \
+  
+     cd .. && podman-compose up -d
+  
+   else
+     echo "Error running user script"
+   fi
 
 runcmd:
   - timedatectl set-timezone Europe/London
   - setsebool -P container_manage_cgroup on
   - chmod +x /root/podman/podman-init.sh
+  - firewall-cmd --zone=public --add-port=8080/tcp
+  - firewall-cmd --zone=public --add-port=8090/tcp
+  - firewall-cmd --reload
+  - loginctl enable-linger 1000
   - sh /root/podman/podman-init.sh
diff --git a/vagrant/Hyper-V/dev-vm/Vagrantfile b/vagrant/Hyper-V/dev-vm/Vagrantfile
--- a/vagrant/Hyper-V/dev-vm/Vagrantfile
+++ b/vagrant/Hyper-V/dev-vm/Vagrantfile
@@ -1,60 +1,58 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 Vagrant.configure("2") do |config|
-  config.vm.box = "generic/debian11"
-  config.vm.hostname = "debian-11-base"
+  config.vm.box = "generic/oracle8"
+  config.vm.hostname = "dev-vm"
 
   config.vm.network "forwarded_port", guest: 8080, host: 8080
   config.vm.network "forwarded_port", guest: 8090, host: 8090
+  config.vm.network "public_network"
 
   config.vm.synced_folder "../../../../azure-challenge-solutions", "/home/vagrant/azure-challenge-solutions"
 
   
-  config.vm.provider "hyper-v" do |v|
-    v.cpus = "2"
-    v.memory = "4096"
-    v.name = "dev-vm"
+  config.vm.provider "hyper-v" do |hv|
+    hv.cpus = "2"
+    hv.memory = "4096"
+    hv.name = "dev-vm"
+    hv.enable_virtualization_extensions = true
+    hv.linked_clone = true
+    hv.gui = true
   end
 
   config.vm.provision "shell", inline: <<-SHELL
-      set -xe
+      set -xeuo pipefail
 
       #Add Timezone'
       ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone && \
       
       #Install packages
-      export DEBIAN_FRONTEND=noninteractive && \
-      apt-get update -y && apt-get dist-upgrade -y && apt-get install -y \
-      apt-transport-https \
-      build-essential \
-      ca-certificates \
-      curl \
-      dbus-user-session \
-      dkms \
-      dos2unix \
-      dnsdiag \
-      git \
-      gnupg-agent \
-      htop \
-      ifupdown \
-      linux-headers-$(uname -r) \
-      locales \
-      nano \
-      neofetch \
-      openssh-server \
-      openssl \
-      podman \
-      pip \
-      sudo \
-      software-properties-common \
-      wget \
-      whois \
-      unzip \
-      vim \
-      zip && \
       
+      yum update -y && \ 
+      yum install -y \
+      yum-utils \
+      git \
+      dnf-plugins-core \
+      curl \
+      git \
+      zip \
+      unzip && \
+
+      yum update -y && \
+      yum install -y \
+      python3-pip \
+      podman \
+      dos2unix \
+      openssl \
+      wget \
+      nano 
+
       #Clean up installs
-      apt-get autoremove && apt-get autoclean && apt-get clean && \
+      yum clean all && \
+
+      firewall-cmd --zone=public --add-port=8080/tcp && \
+      firewall-cmd --zone=public --add-port=8090/tcp && \
+      firewall-cmd --reload
 
       #Configure ssh
       systemctl enable ssh && \
@@ -69,22 +67,23 @@ Vagrant.configure("2") do |config|
 
   config.vm.provision "shell", privileged: false, inline: <<-SHELL
 
-  set -xe
+   set -xeuo pipefail
   
-  if [ "$(command -v pip3)" ]; then
+    if [ "$(command -v pip3)" ]; then
+  
+      export PATH=$PATH:${HOME}/.local/bin && \
 
-    export PATH=$PATH:${HOME}/.local/bin && \
-    source ${HOME}/.bashrc && \
-    pip3 install --user podman-compose && \
-
-    cd azure-challenge-solutions/container/podman/grafana && \
-    mkdir -p grafana-data && \
-    systemctl --user enable --now dbus.socket && \
-    echo "The VM is now setup.  On your host, run vagrant ssh and then  cd azure-challenge-solutions/container/podman/ && podman-compose up -d" && \
-    cd .. && podman-compose up -d
-
-  else
-    echo "Error running user script"
-  fi
+      pip3 install --user podman-compose && \
+  
+      cd azure-challenge-solutions/container/podman/grafana && \
+      mkdir -p grafana-data && \
+      systemctl --user enable --now dbus.socket && \
+      echo "The VM is now setup.  On your host, run vagrant ssh and then  cd azure-challenge-solutions/container/podman/ && podman-compose up -d" && \
+      
+      cd .. && podman-compose up -d
+  
+    else
+      echo "Error running user script"
+    fi
   SHELL
 end
